'use strict';
(()=>{
const g=id=>document.getElementById(id),sa=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),bd=b=>b.scheduled_date||b.preferred_date||'',bt=b=>String(b.scheduled_time||b.preferred_time||'').slice(0,5),active=b=>!['rejected','cancelled'].includes(b.status),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>typeof formatMoney==='function'?formatMoney(+n||0):`${(+n||0).toFixed(2)} ر.س`;
let cal=sa().slice(0,7)+'-01',sel='';
function nav(p){if(typeof navigate==='function')navigate(p)}
function install(){if(g('h2-root'))return;document.body.insertAdjacentHTML('beforeend','<div id="h2-root"></div>');todayUI();calendarUI();searchUI();excelUI();mobileUI();alertsUI();document.addEventListener('click',clicks);refresh();setInterval(()=>document.visibilityState==='visible'&&refresh(),30000)}
function todayUI(){let h=g('page-dashboard')?.querySelector('.page-heading');if(!h)return;h.insertAdjacentHTML('afterend',`<section id="h2Today" class="h2-today"><div class="h2-head"><h3>ملخص اليوم</h3><button id="h2Refresh" class="btn btn-outline">تحديث</button></div><div class="h2-kpis"><article><span>قبض اليوم</span><b id="h2in">—</b></article><article><span>صرف اليوم</span><b id="h2out">—</b></article><article><span>صافي اليوم</span><b id="h2net">—</b></article><article><span>مواعيد اليوم</span><b id="h2book">—</b></article><article><span>بانتظار المراجعة</span><b id="h2pending">—</b></article><article><span>مهام متأخرة</span><b id="h2late">—</b></article></div><div class="h2-two"><div class="card"><div class="card-header"><h3 class="card-title">مواعيد اليوم</h3><button class="btn btn-soft" data-h2page="bookings">عرض الكل</button></div><div id="h2TodayList" class="h2-list"></div></div><div class="card"><div class="card-header"><h3 class="card-title">المهام العاجلة</h3><button class="btn btn-soft" data-h2page="schedule">جدول العمل</button></div><div id="h2TaskList" class="h2-list"></div></div></div></section>`);g('h2Refresh').onclick=refresh}
function renderToday(){if(!g('h2Today')||typeof state==='undefined')return;let t=sa(),e=state.entries||[],b=state.bookings||[],tasks=state.scheduleTasks||[],te=e.filter(x=>x.entry_date===t),i=te.filter(x=>x.entry_type==='incoming').reduce((s,x)=>s+(+x.amount||0),0),o=te.filter(x=>x.entry_type==='outgoing').reduce((s,x)=>s+(+x.amount||0),0),tb=b.filter(x=>active(x)&&bd(x)===t).sort((a,b)=>bt(a).localeCompare(bt(b))),late=tasks.filter(x=>!x.completed&&x.task_date<t);g('h2in').textContent=money(i);g('h2out').textContent=money(o);g('h2net').textContent=money(i-o);g('h2book').textContent=tb.length;g('h2pending').textContent=b.filter(x=>x.status==='pending').length;g('h2late').textContent=late.length;g('h2TodayList').innerHTML=tb.length?tb.slice(0,5).map(x=>`<button class="h2-row" data-book="${esc(x.id)}"><span><b>${esc(bt(x))} — ${esc(x.customer_name)}</b><small>${esc(x.customer_phone)} · ${esc(x.location_label||'')}</small></span>‹</button>`).join(''):'<div class="h2-empty">لا توجد مواعيد اليوم.</div>';let urgent=[...late,...tasks.filter(x=>!x.completed&&x.task_date===t)].slice(0,5);g('h2TaskList').innerHTML=urgent.length?urgent.map(x=>`<button class="h2-row" data-h2page="schedule"><span><b>${esc(x.title||x.task_title||'مهمة')}</b><small>${esc(x.task_date||'')} ${esc(String(x.task_time||'').slice(0,5))}</small></span>‹</button>`).join(''):'<div class="h2-empty">لا توجد مهام عاجلة.</div>'}
function calendarUI(){let s=g('page-bookings')?.querySelector('.booking-stats');if(!s)return;s.insertAdjacentHTML('afterend',`<section id="h2Cal" class="card h2-cal"><div class="card-header"><h3 class="card-title">تقويم مواعيد العملاء</h3><div><button id="h2prev" class="btn btn-outline">السابق</button> <b id="h2cl">—</b> <button id="h2next" class="btn btn-outline">التالي</button></div></div><div class="card-body"><div class="h2-calwrap"><div><div class="h2-week"><span>س</span><span>أ</span><span>إ</span><span>ث</span><span>أر</span><span>خ</span><span>ج</span></div><div id="h2grid" class="h2-grid"></div></div><aside><h4 id="h2daytitle">اختر يومًا</h4><div id="h2daylist" class="h2-list"></div></aside></div></div></section>`);g('h2prev').onclick=()=>move(-1);g('h2next').onclick=()=>move(1)}
function move(n){let d=new Date(cal+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);cal=d.toISOString().slice(0,7)+'-01';sel='';renderCal()}
function renderCal(){let box=g('h2grid');if(!box||typeof state==='undefined')return;let f=new Date(cal+'T12:00:00Z'),y=f.getUTCFullYear(),m=f.getUTCMonth(),last=new Date(Date.UTC(y,m+1,0,12)).getUTCDate(),map={};(state.bookings||[]).filter(active).forEach(x=>{let d=bd(x);if(d?.startsWith(cal.slice(0,7)))(map[d]??=[]).push(x)});g('h2cl').textContent=new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{month:'long',year:'numeric',timeZone:'UTC'}).format(f);box.innerHTML='<span></span>'.repeat((f.getUTCDay()+1)%7)+Array.from({length:last},(_,i)=>{let d=`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`,n=(map[d]||[]).length;return `<button class="h2-day${d===sa()?' today':''}${d===sel?' selected':''}" data-day="${d}"><b>${i+1}</b><small>${n?n+' موعد':'—'}</small></button>`}).join('');box.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{sel=b.dataset.day;renderCal();showDay(sel,map[sel]||[])})}
function showDay(d,rows){g('h2daytitle').textContent=`مواعيد ${d} (${rows.length})`;g('h2daylist').innerHTML=rows.length?rows.sort((a,b)=>bt(a).localeCompare(bt(b))).map(x=>`<button class="h2-row" data-book="${esc(x.id)}"><span><b>${esc(bt(x))} — ${esc(x.customer_name)}</b><small>${esc(x.customer_phone)} · ${esc(x.location_label||'')}</small></span>‹</button>`).join(''):'<div class="h2-empty">لا توجد مواعيد.</div>'}
function searchUI(){let a=document.querySelector('.topbar-actions');if(!a)return;a.insertAdjacentHTML('afterbegin',`<div class="h2-pos"><button id="h2SearchBtn" class="h2-icon"><i class="fa-solid fa-magnifying-glass"></i></button><div id="h2SearchPanel" class="h2-pop"><input id="h2Search" class="input" placeholder="بحث شامل: اسم، جوال، سند، مهمة"><div id="h2Results"></div></div></div>`);g('h2SearchBtn').onclick=e=>{e.stopPropagation();g('h2SearchPanel').classList.toggle('show');g('h2Search').focus()};g('h2Search').oninput=search}
function search(){let q=g('h2Search').value.trim().toLowerCase(),r=[];if(q.length<2){g('h2Results').innerHTML='<div class="h2-empty">اكتب حرفين على الأقل.</div>';return}(state.entries||[]).forEach(x=>{if([x.voucher_number,x.party_name,x.customer_phone,x.reason,x.notes].join(' ').toLowerCase().includes(q))r.push({p:x.entry_type==='incoming'?'incoming':'outgoing',t:`${x.entry_type==='incoming'?'قبض':'صرف'} ${x.voucher_number||''}`,s:`${x.party_name||''} · ${money(x.amount)}`})});(state.bookings||[]).forEach(x=>{if([x.customer_name,x.customer_phone,x.location_label].join(' ').toLowerCase().includes(q))r.push({p:'bookings',id:x.id,t:x.customer_name,s:`${x.customer_phone||''} · ${bd(x)} ${bt(x)}`})});(state.scheduleTasks||[]).forEach(x=>{if([x.title,x.task_title,x.location,x.task_location].join(' ').toLowerCase().includes(q))r.push({p:'schedule',t:x.title||x.task_title,s:`${x.task_date||''} ${x.task_time||''}`})});g('h2Results').innerHTML=r.slice(0,20).map((x,i)=>`<button class="h2-result" data-ri="${i}"><b>${esc(x.t)}</b><small>${esc(x.s)}</small></button>`).join('')||'<div class="h2-empty">لا توجد نتائج.</div>';g('h2Results').querySelectorAll('[data-ri]').forEach(b=>b.onclick=()=>{let x=r[+b.dataset.ri];nav(x.p);g('h2SearchPanel').classList.remove('show');if(x.id&&typeof openBookingAdminModal==='function')setTimeout(()=>openBookingAdminModal(x.id),100)})}
function excelUI(){let t=g('page-activity')?.querySelector('.tools-grid');if(!t)return;t.insertAdjacentHTML('afterbegin',`<div class="tool-box"><h3>مركز Excel المتقدم</h3><p>تصدير حسب الفترة والنوع وطريقة الدفع والعميل بدون تعديل البيانات.</p><div class="h2-excel"><input id="h2xf" class="input" type="date"><input id="h2xt" class="input" type="date"><select id="h2xtype" class="select"><option value="all">كل السندات</option><option value="incoming">قبض</option><option value="outgoing">صرف</option></select><select id="h2xpay" class="select"><option value="all">كل طرق الدفع</option><option value="cash">نقدي</option><option value="bank_transfer">تحويل بنكي</option><option value="card">بطاقة</option><option value="cheque">شيك</option></select><input id="h2xq" class="input" placeholder="اسم / جهة / رقم سند"><button id="h2Export" class="btn btn-success"><i class="fa-solid fa-file-excel"></i> تصدير التقرير</button></div><p id="h2xcount" class="h2-muted"></p></div>`);['h2xf','h2xt','h2xtype','h2xpay','h2xq'].forEach(id=>g(id).oninput=countX);g('h2Export').onclick=exportX}
function xrows(){let f=g('h2xf')?.value||'',t=g('h2xt')?.value||'',ty=g('h2xtype')?.value||'all',p=g('h2xpay')?.value||'all',q=(g('h2xq')?.value||'').toLowerCase();return(state.entries||[]).filter(x=>(!f||x.entry_date>=f)&&(!t||x.entry_date<=t)&&(ty==='all'||x.entry_type===ty)&&(p==='all'||x.payment_method===p)&&(!q||[x.voucher_number,x.party_name,x.company_name,x.customer_phone,x.reason].join(' ').toLowerCase().includes(q)))}
function countX(){if(g('h2xcount'))g('h2xcount').textContent=`${xrows().length} سند مطابق`}
async function exportX(){let b=g('h2Export'),r=xrows();if(!r.length){showToast?.('لا توجد بيانات','غيّر خيارات التصدير','error');return}b.disabled=true;let old=b.innerHTML;b.textContent='جاري التصدير...';try{let bytes=await HulullExcel.create(r,`تقرير مخصص ${g('h2xf').value||'البداية'} — ${g('h2xt').value||'اليوم'}`),blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`Hulull-report-${sa()}.xlsx`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);showToast?.('تم تجهيز Excel',`تم تصدير ${r.length} سند`)}catch(e){showToast?.('تعذر التصدير',e.message||'أعد المحاولة','error')}finally{b.disabled=false;b.innerHTML=old}}
function mobileUI(){document.body.insertAdjacentHTML('beforeend',`<nav id="h2Mobile" class="h2-mobile"><button data-h2page="dashboard"><i class="fa-solid fa-house"></i><span>الرئيسية</span></button><button data-h2page="bookings"><i class="fa-solid fa-calendar-check"></i><span>المواعيد</span></button><button data-h2page="incoming"><i class="fa-solid fa-arrow-down"></i><span>قبض</span></button><button data-h2page="outgoing"><i class="fa-solid fa-arrow-up"></i><span>صرف</span></button><button data-h2page="activity"><i class="fa-solid fa-ellipsis"></i><span>المزيد</span></button></nav>`)}
function alertsUI(){let a=document.querySelector('.topbar-actions');if(!a)return;a.insertAdjacentHTML('afterbegin',`<div class="h2-pos"><button id="h2Bell" class="h2-icon"><i class="fa-regular fa-bell"></i><span id="h2badge" class="h2-badge hidden">0</span></button><div id="h2Alerts" class="h2-pop"><div class="h2-pophead"><b>التنبيهات الذكية</b></div><div id="h2AlertList" class="h2-list"></div></div></div>`);g('h2Bell').onclick=e=>{e.stopPropagation();g('h2Alerts').classList.toggle('show')}}
function renderAlerts(){if(!g('h2AlertList'))return;let t=sa(),tom=(()=>{let d=new Date(t+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)})(),b=state.bookings||[],tasks=state.scheduleTasks||[],a=[],p=b.filter(x=>x.status==='pending').length,tm=b.filter(x=>active(x)&&bd(x)===tom).length,l=tasks.filter(x=>!x.completed&&x.task_date<t).length,td=tasks.filter(x=>!x.completed&&x.task_date===t).length;if(p)a.push(['bookings',`${p} طلب بانتظار المراجعة`]);if(tm)a.push(['bookings',`${tm} موعد بكرة`]);if(l)a.push(['schedule',`${l} مهمة متأخرة`]);if(td)a.push(['schedule',`${td} مهمة متبقية اليوم`]);g('h2badge').textContent=a.length;g('h2badge').classList.toggle('hidden',!a.length);g('h2AlertList').innerHTML=a.length?a.map(x=>`<button class="h2-row" data-h2page="${x[0]}"><span><b>${x[1]}</b><small>اضغط للمتابعة</small></span>‹</button>`).join(''):'<div class="h2-empty">ما عندك تنبيهات مهمة حاليًا.</div>'}
function clicks(e){let p=e.target.closest('[data-h2page]');if(p){nav(p.dataset.h2page);g('h2Alerts')?.classList.remove('show')}let b=e.target.closest('[data-book]');if(b&&typeof openBookingAdminModal==='function')openBookingAdminModal(b.dataset.book);if(!e.target.closest('#h2SearchPanel')&&!e.target.closest('#h2SearchBtn'))g('h2SearchPanel')?.classList.remove('show');if(!e.target.closest('#h2Alerts')&&!e.target.closest('#h2Bell'))g('h2Alerts')?.classList.remove('show')}
function refresh(){if(typeof state==='undefined')return;renderToday();renderCal();renderAlerts();countX()}
function wait(){if(document.readyState==='loading')return document.addEventListener('DOMContentLoaded',()=>setTimeout(wait,0),{once:true});if(typeof state==='undefined'||typeof navigate!=='function')return setTimeout(wait,100);install()}
wait();window.Hulull2={refresh};
})();
